#!/usr/bin/env python3
"""Generate the forwarding stubs and .def file for the opengl32.dll proxy.

Every export of the system opengl32.dll gets a tiny x86 stub that jumps to the
real function (resolved lazily on first call). Functions listed in HOOKED are
exported from C code in glfix.c instead; the stub for them still exists so the
C code can call the real function through real_table.

Usage: gen_exports.py exports.txt outdir
"""
import os
import sys

HOOKED = {"glPushAttrib", "glPopAttrib", "glNewList", "glEndList"}


def main():
    exports_path, outdir = sys.argv[1], sys.argv[2]
    exports = []
    with open(exports_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            name, argbytes = line.split("@")
            exports.append((name, int(argbytes)))

    os.makedirs(outdir, exist_ok=True)

    with open(os.path.join(outdir, "stubs.S"), "w") as s:
        s.write("/* generated by gen_exports.py - do not edit */\n")
        s.write("\t.text\n")
        for i, (name, _) in enumerate(exports):
            s.write(f"\t.globl _fwd_{name}\n")
            s.write(f"_fwd_{name}:\n")
            s.write(f"\tmovl _real_table+{4 * i}, %eax\n")
            s.write("\ttestl %eax, %eax\n")
            s.write("\tjz 1f\n")
            s.write("\tjmp *%eax\n")
            s.write(f"1:\tpushl ${i}\n")
            s.write("\tcall _glfix_resolve\n")
            s.write("\taddl $4, %esp\n")
            s.write("\tjmp *%eax\n")

    with open(os.path.join(outdir, "opengl32.def"), "w") as d:
        d.write("LIBRARY opengl32.dll\nEXPORTS\n")
        for name, argbytes in exports:
            if name in HOOKED:
                d.write(f"\t{name}={name}_hook@{argbytes}\n")
            else:
                d.write(f"\t{name}=fwd_{name}\n")

    with open(os.path.join(outdir, "exports.h"), "w") as h:
        h.write("/* generated by gen_exports.py - do not edit */\n")
        h.write(f"#define GLFIX_EXPORT_COUNT {len(exports)}\n")
        h.write("static const char *const export_names[] = {\n")
        for name, _ in exports:
            h.write(f'\t"{name}",\n')
        h.write("};\n")
        for i, (name, _) in enumerate(exports):
            h.write(f"#define IDX_{name} {i}\n")


if __name__ == "__main__":
    main()
